# Generated by Django 3.2.16 on 2023-07-24 12:42

import django.db.models.deletion
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230716_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, validators=[users.validators.validate_name], verbose_name='Наименование ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
