# Generated by Django 3.2.16 on 2023-07-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингредиентов рецепта'},
        ),
    ]
