# Generated by Django 3.2.16 on 2023-07-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_follow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('created',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
